### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by risBo-ai** [bitpay/bitpay-checkout-for-woocommerce#46]
You should fix php error, many plugins don't support yet 8.1. Here is error:

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

**Comment by bobbrodie** [comment]
@risBo-ai just making a note that you've also reported this here: https://wordpress.org/support/topic/php-error-composer/ so others can see the progress.

This is due to one of our sub-dependencies, so we've updated our SDK to address the core issue (we now run PHPUnit 9 _and_ 10 in our SDK).

We'll support PHP 8.0 until 2023-11-26 and then our minimum will be 8.1.

**Comment by bobbrodie** [comment]
@risBo-ai just a heads up, this is merged. I've updated the support thread on WordPress.org, and will keep this open for a day or two. We’ve tested Composer with PHP 8.0, and tested the plugin. We have not run into any issues but definitely let us know if you come across anything.

**Comment by risBo-ai** [comment]
Thanks, it seems that issue is fixed. I appreciate

**Comment by bobbrodie** [comment]
Thanks again for reporting, this led us to that update in the SDK. It's good to have this out!
