### ISSUE TITLE
What is the close url and how to activate with url redirect

### ISSUE THREAD

**Issue by atlanteavila** [bitpay/bitpay-checkout-for-woocommerce#65]
Hi all,

I'm sorry if I'm missing something here, but I can't find a reference anywhere as to how to set up the bitpay plugin to work without the modal. Currently the modal is not working for my site, it worked with redirect, but I can't figure out what is a close url, and what it should cotain within that page. (I'm assuming it's a page). I can't seem to find any inforation ont the plugin's documentation. Any help would be greatly appreciated!

**Comment by shaunek-hero** [comment]
Our developer also mentioned that he couldn't get the mode with modal working, so he had to use the redirect mode. This is fine but we think we would have preferred using the modal mode.

**Comment by p-maguire** [comment]
@atlanteavila The close URL is an optional field that allows an Admin to choose where BitPay directs the User back to your site, after they close the BitPay Invoice screen (Note: Because the BitPay flow works like an offline payment method, this is not the same as a User completing the BitPay payment, since the Invoice is payable for 15 minutes after creation)

We've made some improvements to this plugin with the last few releases and the Modal should work as expected now. If you have any further issues, feel free to create a new Issue and we'll take a look!
